logging:
    level:
        org:
            hibernate:
                orm:
                    jdbc:
                        bind: trace
        root: info
mybatis:
    mapper-locations: classpath:mappers/**/*.xml
server:
    port: 8080
    servlet:
        context-path: /
spring:
    servlet:
        multipart:
            location: uploads
            max-file-size: 10MB
    mail:
        host: smtp.gmail.com
        port: 587
        username: wkdalsgur5556@gmail.com
        password: mekvhlulqwvlgcjj
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true
    application:
        name: greendae
        version: version 0.0.5
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Qwerty123@
        url: jdbc:mysql://13.209.74.140:3306/greendae
        username: greendae
    devtools:
        livereload:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    thymeleaf:
        prefix: classpath:/templates
